# Generated by Django 2.1.1 on 2018-09-19 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180918_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
