# Generated by Django 2.1.1 on 2018-09-20 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_video_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollywood',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
