# Generated by Django 2.1.1 on 2018-09-20 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180920_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollywood',
            name='bollydetails',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartoon',
            name='cardetails',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hollywood',
            name='hollydetails',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
